"use client"

import type React from "react"
import { createContext, useContext, useEffect, useState } from "react"

type Language = "en" | "th"

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    "nav.home": "Home",
    "nav.diagnosis": "Diagnosis",
    "nav.knowledge": "Knowledge",
    "nav.dashboard": "Dashboard",
    "nav.admin": "Admin",
    "nav.login": "Login",
    "nav.logout": "Logout",
    "nav.register": "Register",
    "nav.about": "About Us",
    "nav.alerts": "Alerts",
    "nav.alertsEmpty": "No new alerts.",
    "nav.alertsDisabled": "Disease alerts are paused for this account.",
    "nav.alertsHistory": "History",
    "nav.alertsHistoryEmpty": "No read alerts yet.",
    "nav.alertsDetail.published": "Published",

    // Home Page
    "home.title": "AgriSense",
    "home.subtitle": "AI System for Plant Disease Detection",
    "home.description":
      "Advanced AI technology to help farmers quickly identify plant diseases and get expert care recommendations.",
    "home.start": "Start Diagnosis",
    "home.features.fast": "Fast Diagnosis",
    "home.features.fast.desc": "Get results in seconds with our advanced AI",
    "home.features.remote": "Remote Access",
    "home.features.remote.desc": "Diagnose from anywhere, anytime",
    "home.features.cost": "Cost Effective",
    "home.features.cost.desc": "Save money on expensive consultations",
    "home.stats.completed": "Diagnoses Completed",
    "home.stats.accuracy": "Accuracy Rate",
    "home.stats.detected": "Plant Diseases Detected",

    // Auth
    "auth.welcomeTitle": "Welcome to AgriSense",
    "auth.welcomeSubtitle": "Sign in to your account",
    "auth.loginTitle": "Login",
    "auth.loginDescription": "Enter your email and password to access your account",
    "auth.fillFieldsError": "Please fill in all fields",
    "auth.invalidError": "Invalid email or password",
    "auth.accountCreated": "Account created successfully. Please sign in.",
    "auth.signIn": "Sign In",
    "auth.signingIn": "Signing in...",
    "auth.noAccount": "Don't have an account?",
    "auth.signUpHere": "Sign up here",
    "auth.registerTitle": "Join AgriSense",
    "auth.registerSubtitle": "Create your account to get started",
    "auth.registerCardTitle": "Create Account",
    "auth.registerCardDescription": "Fill in your information to register",
    "auth.fullNameLabel": "Username",
    "auth.fullNamePlaceholder": "Choose a username",
    "auth.emailLabel": "Email",
    "auth.passwordLabel": "Password",
    "auth.confirmPasswordLabel": "Confirm Password",
    "auth.roleLabel": "Role",
    "auth.role.farmer": "Farmer",
    "auth.role.expert": "Agricultural Expert",
    "auth.registerButton": "Create Account",
    "auth.registering": "Creating account...",
    "auth.haveAccount": "Already have an account?",
    "auth.signInHere": "Sign in here",
    "auth.passwordMismatch": "Passwords do not match",
    "auth.passwordTooShort": "Password must be at least 6 characters long",
    "auth.registerFailed": "Registration failed. Please try again.",

    // Diagnosis Page
    "diagnosis.title": "Plant Disease Diagnosis",
    "diagnosis.subtitle": "Results are saved automatically once the analysis finishes",
    "diagnosis.upload": "Upload Leaf Image",
    "diagnosis.uploadHint": "Upload a clear image of the plant leaf for analysis",
    "diagnosis.analyze": "Analyze",
    "diagnosis.result": "Diagnosis Result",
    "diagnosis.resultHint": "AI analysis results will appear here",
    "diagnosis.disease": "Disease",
    "diagnosis.severity": "Severity",
    "diagnosis.recommendation": "Care Recommendation",
    "diagnosis.save": "Save Diagnosis",
    "diagnosis.historyTitle": "Recent Analyses",
    "diagnosis.historyDescription": "This list updates automatically after the model finishes processing",
    "diagnosis.predictError": "Unable to call the image analysis service",
    "diagnosis.uploadSuccess": "Image uploaded successfully",
    "diagnosis.supportedTitle": "Our AI now supports",
    "diagnosis.crop.rice": "Rice",
    "diagnosis.crop.sugarcane": "Sugar Cane",
    "diagnosis.crop.durian": "Durian",
    "diagnosis.historySaved": "This result has been saved to your history",
    "diagnosis.loginRequiredTitle": "Please sign in to start",
    "diagnosis.loginRequiredDescription":
      "Sign in or register for free to save scan history and receive personalized recommendations.",
    "diagnosis.loginRequiredRegister": "Register",
    "diagnosis.loginRequiredLogin": "Login",
    "diagnosis.changeImage": "Change Image",
    "diagnosis.loginToSaveHint": "Please sign in to save results to your history",

    // Knowledge Page
    "knowledge.title": "Plant Care Knowledge",
    "knowledge.prevention": "Disease Prevention",
    "knowledge.watering": "Watering Guidelines",
    "knowledge.fertilizer": "Fertilizer Usage",
    "knowledge.pest": "Pest Control",

    // Disease Library
    "diseases.title": "Restricted Disease Library",
    "diseases.subtitle":
      "Internal knowledge base for Agrisense experts and admins. Reference these profiles after the AI model flags a disease.",
    "diseases.searchLabel": "Search",
    "diseases.searchPlaceholder": "Search by Thai or English name, symptoms, or tags",
    "diseases.cropLabel": "Crop focus",
    "diseases.filters.all": "All crops",
    "diseases.filters.durian": "Durian",
    "diseases.filters.sugarcane": "Sugarcane",
    "diseases.filters.rice": "Rice",
    "diseases.loading": "Loading curated disease profiles...",
    "diseases.empty": "No disease records match your filters yet.",
    "diseases.accessDeniedTitle": "Expert clearance required",
    "diseases.accessDeniedDescription":
      "Only Agrisense experts and administrators can view the curated disease intelligence.",
    "diseases.contactCta": "Contact administrator",
    "diseases.spread.high": "High spread risk",
    "diseases.spread.medium": "Moderate spread risk",
    "diseases.spread.low": "Low spread risk",
    "diseases.severityLabel": "Severity {score}/5",
    "diseases.symptoms": "Key symptoms",
    "diseases.treatment": "Recommended response",
    "diseases.prevention": "Preventive actions",
    "diseases.noOverview": "No overview has been documented yet.",
    "diseases.causes": "Causal factors",
    "diseases.addRecord": "Add disease",
    "diseases.form.title": "Add new disease profile",
    "diseases.form.description":
      "Document Thai crop diseases in detail so experts and future AI training pipelines share the same ground truth.",
    "diseases.form.severity": "Severity score (1-5)",
    "diseases.form.spreadRisk": "Spread risk",
    "diseases.form.pathogenType": "Pathogen type",
    "diseases.form.nameTh": "Thai name",
    "diseases.form.nameEn": "English/common name",
    "diseases.form.overview": "Short overview",
    "diseases.form.listPlaceholder": "One line per item",
    "diseases.form.listHelper": "Each line will be saved as an individual bullet.",
    "diseases.form.triggers": "Field observations / triggers",
    "diseases.form.tags": "Tags",
    "diseases.form.tagsHelper": "Comma separated e.g. leaf spot, fungal",
    "diseases.form.sources": "Source references",
    "diseases.form.sourcesHelper": "Format each line as Label | https://example.com",
    "diseases.form.submit": "Save profile",
    "diseases.form.missingRequired":
      "Please provide the Thai name plus at least one symptom, cause, and treatment entry.",
    "diseases.form.genericError": "Unable to save disease profile",

    // Dashboard
    "dashboard.title": "User Dashboard",
    "dashboard.adminProfilesTitle": "Admin Profiles",
    "dashboard.profile": "Profile",
    "dashboard.history": "Scan History",
    "dashboard.historyTitle": "Scan History",
    "dashboard.alerts": "Disease Alerts",
    "dashboard.settings": "Settings",
    "dashboard.loginPromptTitle": "Please sign in",
    "dashboard.loginPromptDescription": "Sign in to view your analysis history and personalized stats.",
    "dashboard.loginPromptHint": "If you don't have an account yet, you can sign up for free to start saving your plant diagnoses.",
    "dashboard.memberSince": "Member since",
    "dashboard.profileDescription": "Current membership details and quick settings",
    "dashboard.anonymousUser": "Unnamed user",
    "dashboard.profilePlan": "Plan",
    "dashboard.manageProfile": "Manage Profile",
    "dashboard.defaultRole": "Farmer",
    "dashboard.statsCardTitle": "Latest Analytics",
    "dashboard.statsTotal": "Total scans",
    "dashboard.statsCompleted": "Completed analyses",
    "dashboard.statsHealthy": "Healthy outcomes",
    "dashboard.statsHighRisk": "High risk alerts",
    "dashboard.role.farmer": "Farmer",
    "dashboard.role.expert": "Agricultural Expert",
    "dashboard.role.admin": "Admin",
    "dashboard.plan.free": "Free",
    "dashboard.plan.pro": "Pro",
    "dashboard.plan.enterprise": "Enterprise",
    "dashboard.historyDescription": "This list updates automatically after each diagnosis completes.",
    "dashboard.status.pending": "Pending",
    "dashboard.status.processing": "Processing",
    "dashboard.status.completed": "Completed",
    "dashboard.status.failed": "Failed",
    "dashboard.severity.high": "High severity",
    "dashboard.severity.medium": "Medium severity",
    "dashboard.severity.low": "Low severity",
    "dashboard.severity.none": "No issues",
    "dashboard.confidenceShort": "Confidence {value}%",
    "dashboard.pendingAnalysis": "Pending analysis",
    "dashboard.loadingScans": "Loading recent analyses...",
    "dashboard.historyEmpty": "No analysis history yet. Try running a diagnosis from the scanner page.",
    "dashboard.unknownTime": "Unknown time",
    "dashboard.viewDetails": "View scan details",
    "dashboard.deleteResult": "Delete result",
    "dashboard.tipsTitle": "Latest Recommendations",
    "dashboard.tipsDescription": "This section updates whenever you add new analyses.",
    "dashboard.tipsBody": "Use this dashboard to track each analysis, monitor high-risk warnings, and act on AI guidance quickly to keep your crops healthy.",
    "dashboard.tipsHint": "Tip: If results repeat, capture more angles and add notes to help experts review further.",
    "dashboard.profileDialogTitle": "Manage Profile",
    "dashboard.profileDialogDescription": "Upload or replace your profile photo. We'll optimize it automatically.",
    "dashboard.profileDialogGuideline": "Use a square image up to 4MB (JPG, PNG, or WEBP).",
    "dashboard.profileDialogInputLabel": "Choose a new photo",
    "dashboard.profileDialogInputHelp": "We will resize and compress the image so it doesn't waste storage.",
    "dashboard.profileDialogSave": "Save photo",
    "dashboard.detailDialogTitle": "Scan Details",
    "dashboard.detailDialogDescription": "Review the insights from each analysis.",
    "dashboard.detailResult": "Diagnosis",
    "dashboard.detailStatus": "Status",
    "dashboard.detailSeverity": "Severity",
    "dashboard.detailConfidence": "Confidence",
    "dashboard.detailSubmittedAt": "Submitted at",
    "dashboard.detailProcessedAt": "Processed at",
    "dashboard.detailCapturedAt": "Captured at",
    "dashboard.detailModelVersion": "Model version",
    "dashboard.detailLocation": "Location",
    "dashboard.detailLocationAccuracy": "±{meters}m accuracy",
    "dashboard.detailFailureReason": "Failure reason:",
    "dashboard.detailNotes": "Notes",
    "dashboard.detailImage": "Uploaded image",
    "dashboard.detailOpenFullImage": "Open full resolution",
    "dashboard.detailMetadata": "Metadata",
    "dashboard.metadata.localeDisease": "Local disease name",
    "dashboard.metadata.severity": "Severity",
    "dashboard.metadata.severityLocal": "Local severity",
    "dashboard.detailRawData": "View raw model data",
    "dashboard.detailEmptyState": "Select a scan from the list to view details.",
    "dashboard.deleteConfirmTitle": "Delete analysis result",
    "dashboard.deleteConfirmDescription": "Deleting \"{result}\" will remove it from history and cannot be undone.",
    "dashboard.deleteConfirmAction": "Delete result",
    "dashboard.deletingStatus": "Deleting...",
    "dashboard.uploadingAvatar": "Uploading...",
    "dashboard.errorLoadHistory": "Unable to load scan history",
    "dashboard.errorLoadDetail": "Unable to fetch scan details",
    "dashboard.errorDelete": "Unable to delete the scan result. Please try again.",
    "dashboard.avatarErrorNotLoggedInTitle": "Sign in required",
    "dashboard.avatarErrorNotLoggedInDescription": "Please sign in before changing your profile photo.",
    "dashboard.avatarErrorNoFileTitle": "No image selected",
    "dashboard.avatarErrorNoFileDescription": "Choose a photo before saving.",
    "dashboard.avatarErrorTypeTitle": "Unsupported file type",
    "dashboard.avatarErrorTypeDescription": "Please upload a PNG, JPG, or WEBP image.",
    "dashboard.avatarErrorSizeTitle": "File is too large",
    "dashboard.avatarErrorSizeDescription": "Profile photos must be 4MB or smaller.",
    "dashboard.avatarSuccessTitle": "Profile updated",
    "dashboard.avatarSuccessDescription": "We optimized and saved your new photo.",
    "dashboard.avatarFailTitle": "Upload failed",
    "dashboard.avatarFailDescription": "We couldn't upload your photo. Please try again.",
    "dashboard.note.healthy": "Plant appears healthy. Continue regular care and monitoring.",
    "dashboard.note.healthyShort": "Plant appears healthy. Continue regular care.",
    "dashboard.note.lowSeverity": "Low severity detected. Keep monitoring and maintain good plant care practices.",
    "dashboard.note.highSeverity": "High severity detected. Consider immediate treatment and closer monitoring.",
    "dashboard.note.mediumSeverity": "Medium severity detected. Monitor closely and consider targeted treatment.",

    // About
    "about.title": "What is Agrisense",
    "about.p1":
      "Agrisense is an AI-powered platform designed to help farmers and plant lovers diagnose plant diseases quickly and accurately using image analysis.",
    "about.p2":
      "By simply uploading a photo, users can receive insights, care tips, and preventive measures to keep their crops healthy — anytime, anywhere.",
    "about.p3":
      "Our mission is to empower sustainable agriculture through intelligent technology, making plant health management easy, accessible, and efficient for everyone.",
    "about.team": "Our team",

    // Admin
    "admin.title": "Admin Panel",
    "admin.subtitle": "Use the shared login channel to manage elevated permissions and critical updates.",
    "admin.diseases": "Manage Diseases",
    "admin.users": "User Management",
    "admin.userCardDescription": "Promote trusted members to admin or downgrade them instantly.",
    "admin.analytics": "System Analytics",
    "admin.alerts": "Send Alerts",
    "admin.loginRequiredTitle": "Sign in to continue",
    "admin.loginRequiredDescription":
      "The admin console uses the same login flow as every user. Sign in with your Agrisen account to continue.",
    "admin.noPermissionTitle": "Admin privileges required",
    "admin.noPermissionDescription":
      "Only administrator accounts can access this page. Ask the primary admin to upgrade your role.",
    "admin.loadError": "Unable to load users",
    "admin.logLoadError": "Unable to load admin log",
    "admin.metrics.users": "Total users",
    "admin.metrics.admins": "Administrators",
    "admin.metrics.experts": "Experts",
    "admin.heroLabel": "Administrator",
    "admin.heroTitle": "Control Center",
    "admin.heroSubtitle": "Monitor permissions, knowledge, and audit trails for the Agrisense platform in one hub.",
    "admin.settingsPanelTitle": "Settings",
    "admin.settingsPanelSubtitle": "Navigate between moderation tools.",
    "admin.notification": "Notification",
    "admin.notification.allow": "Allow",
    "admin.notification.mute": "Mute",
    "admin.notificationStatusUpdated": "Notification preference updated.",
    "admin.profileSaved": "Profile saved",
    "admin.profileSavedDescription": "Changes are synced across the admin console.",
    "admin.profilePassword": "Your Password",
    "admin.profileLocation": "Location",
    "admin.profileSaveCta": "Save Change",
    "admin.quickLinks.title": "Workspace shortcuts",
    "admin.quickLinks.subtitle": "Jump straight to critical monitoring tools.",
    "admin.quickLinks.logs": "Admin log",
    "admin.quickLinks.logsDesc": "Review every recorded moderation action.",
    "admin.quickLinks.alerts": "Broadcast alerts",
    "admin.quickLinks.alertsDesc": "Jump to the disease alert announcement panel.",
    "admin.quickLinks.diseases": "Disease intelligence (experts only)",
    "admin.quickLinks.diseasesDesc": "Open the restricted Thai crop disease library.",
    "admin.alertComposer.title": "Create disease alert",
    "admin.alertComposer.description": "Publish urgent disease information to all users. Alerts appear under the profile notification center.",
    "admin.alertComposer.topic": "Alert title",
    "admin.alertComposer.body": "Details",
    "admin.alertComposer.image": "Attach image (optional)",
    "admin.alertComposer.publish": "Publish alert",
    "admin.alertComposer.success": "Alert published",
    "admin.alertComposer.error": "Unable to publish alert",
    "admin.alertCenter.title": "Alert center",
    "admin.alertCenter.description": "Review published alerts, delete outdated updates, or create a new broadcast.",
    "admin.alertCenter.listTitle": "Published alerts",
    "admin.alertCenter.empty": "No alerts have been published yet.",
    "admin.alertCenter.newAlert": "Create announcement",
    "admin.alertCenter.backToList": "Back to alert center",
    "admin.alertCenter.deleteSuccess": "Alert removed",
    "admin.alertCenter.deleteError": "Unable to delete alert",
    "admin.alertCenter.publishedLabel": "Published",
    "admin.quickLinks.roles": "Manage users",
    "admin.quickLinks.rolesDesc": "Promote or demote accounts (restricted to the primary admin).",
    "admin.logRetentionNote": "All admin actions are stored for auditing at any time.",
    "admin.roleManager.title": "Manage user roles",
    "admin.roleManager.subtitle":
      "Only the designated primary admin can assign or revoke administrative rights.",
    "admin.roleManager.permissionWarning":
      "You must be signed in with the primary admin credentials to change member roles.",
    "admin.roleManager.searchPlaceholder": "Search by name or email",
    "admin.roleManager.saveSuccess": "Role updated",
    "admin.roleManager.saveError": "Unable to update role",
    "admin.roleManager.grantedAdmin": "has been promoted to administrator.",
    "admin.roleManager.revokedAdmin": "has been set as a regular user.",
    "admin.roleManager.auditHint": "All changes are logged in the admin activity history.",
    "admin.role.user": "User",
    "admin.role.admin": "Admin",
    "dashboard.alertsEmpty": "No alerts have been published yet.",
    "admin.searchPlaceholder": "Search name or email...",
    "admin.search": "Search",
    "admin.refresh": "Refresh",
    "admin.table.name": "Name",
    "admin.table.email": "Email",
    "admin.table.role": "Role",
    "admin.table.plan": "Plan",
    "admin.table.joined": "Joined",
    "admin.table.access": "Access",
    "admin.emptyState": "No matching users yet. Try another search.",
    "admin.primaryBadge": "Primary admin",
    "admin.primaryInstructionsTitle": "Primary administrator",
    "admin.primaryInstructionsDescription":
      "The primary admin account is responsible for granting or revoking administrator rights.",
    "admin.primaryInstructionsBody":
      "Contact the security lead or use your authorized admin credentials to update roles in this list.",
    "admin.tip.signIn": "Use your approved admin credentials to unlock this page.",
    "admin.primaryAccountLabel": "Primary admin (confidential)",
    "admin.tip.trust": "Grant admin rights only to trusted team members.",
    "admin.tip.downgrade": "Downgrade roles instantly if access is no longer needed.",
    "admin.promoteSuccess": "Permissions updated",
    "admin.promoteError": "Unable to update permissions",
    "admin.logTitle": "Admin activity log",
    "admin.logDescription": "Every elevated action performed by administrators is recorded here for transparency.",
    "admin.log.table.actor": "Admin",
    "admin.log.table.action": "Action",
    "admin.log.table.target": "Target",
    "admin.log.table.timestamp": "Timestamp",
    "admin.log.empty": "No admin activity yet.",
    "admin.log.loading": "Loading latest admin log...",
    "admin.log.action.promote": "Grant admin rights",
    "admin.log.action.demote": "Remove admin rights",
    "admin.log.action.update": "Role updated",
    "admin.log.action.custom": "Admin action",
    "admin.log.action.alertPublish": "Published disease alert",
    "admin.log.unknownTarget": "Unknown target",

    // Common
    "common.save": "Save",
    "common.cancel": "Cancel",
    "common.edit": "Edit",
    "common.delete": "Delete",
    "common.loading": "Loading...",
    "common.name": "Name",
    "common.refresh": "Refresh",
    "common.error": "Error occurred",
    "common.success": "Success",
    "common.close": "Close",
  },
  th: {
    // Navigation
    "nav.home": "หน้าแรก",
    "nav.diagnosis": "วินิจฉัย",
    "nav.knowledge": "ความรู้",
    "nav.dashboard": "แดชบอร์ด",
    "nav.admin": "ผู้ดูแล",
    "nav.login": "เข้าสู่ระบบ",
    "nav.logout": "ออกจากระบบ",
    "nav.register": "สมัครสมาชิก",
    "nav.about": "เกี่ยวกับเรา",
    "nav.alerts": "การแจ้งเตือน",
    "nav.alertsEmpty": "ยังไม่มีการแจ้งเตือนใหม่",
    "nav.alertsDisabled": "ระบบแจ้งเตือนโรคถูกปิดอยู่",
    "nav.alertsHistory": "ประวัติ",
    "nav.alertsHistoryEmpty": "ยังไม่มีการแจ้งเตือนที่อ่านแล้ว",
    "nav.alertsDetail.published": "เผยแพร่",

    // Home Page
    "home.title": "AgriSense",
    "home.subtitle": "ระบบ AI สำหรับตรวจจับโรคพืช",
    "home.description": "เทคโนโลยี AI ขั้นสูงเพื่อช่วยเกษตรกรระบุโรคพืชได้อย่างรวดเร็วและได้รับคำแนะนำการดูแลจากผู้เชี่ยวชาญ",
    "home.start": "เริ่มวินิจฉัย",
    "home.features.fast": "วินิจฉัยรวดเร็ว",
    "home.features.fast.desc": "ได้ผลลัพธ์ในไม่กี่วินาทีด้วย AI ขั้นสูง",
    "home.features.remote": "เข้าถึงระยะไกล",
    "home.features.remote.desc": "วินิจฉัยได้ทุกที่ทุกเวลา",
    "home.features.cost": "ประหยัดค่าใช้จ่าย",
    "home.features.cost.desc": "ประหยัดเงินจากการปรึกษาที่แพง",
    "home.stats.completed": "การวินิจฉัยที่เสร็จสิ้น",
    "home.stats.accuracy": "อัตราความแม่นยำ",
    "home.stats.detected": "โรคพืชที่ตรวจพบ",

    // Diagnosis Page
    "diagnosis.title": "วินิจฉัยโรคพืช",
    "diagnosis.subtitle": "ผลลัพธ์จะถูกบันทึกลงฐานข้อมูลอัตโนมัติเมื่อการวิเคราะห์เสร็จสิ้น",
    "diagnosis.upload": "อัปโหลดรูปใบข้าว",
    "diagnosis.uploadHint": "อัปโหลดรูปใบข้าวให้ชัดเพื่อใช้วิเคราะห์",
    "diagnosis.analyze": "วิเคราะห์",
    "diagnosis.result": "ผลการวินิจฉัย",
    "diagnosis.resultHint": "ผลการวิเคราะห์จาก AI จะแสดงที่นี่",
    "diagnosis.disease": "โรค",
    "diagnosis.severity": "ความรุนแรง",
    "diagnosis.recommendation": "คำแนะนำการดูแล",
    "diagnosis.save": "บันทึกการวินิจฉัย",
    "diagnosis.historyTitle": "ประวัติการวิเคราะห์ล่าสุด",
    "diagnosis.historyDescription": "รายการนี้จะอัปเดตอัตโนมัติหลังจากโมเดลประมวลผลเสร็จสิ้น",
    "diagnosis.predictError": "ไม่สามารถเรียกใช้บริการวิเคราะห์ภาพได้",
    "diagnosis.uploadSuccess": "อัปโหลดรูปเรียบร้อย",
    "diagnosis.supportedTitle": "ขณะนี้ AI รองรับ",
    "diagnosis.crop.rice": "ข้าว",
    "diagnosis.crop.sugarcane": "อ้อย",
    "diagnosis.crop.durian": "ทุเรียน",
    "diagnosis.historySaved": "ผลลัพธ์นี้ถูกบันทึกลงในประวัติของคุณแล้ว",
    "diagnosis.loginRequiredTitle": "กรุณาเข้าสู่ระบบก่อนเริ่มวิเคราะห์",
    "diagnosis.loginRequiredDescription":
      "ลงชื่อเข้าใช้หรือสมัครสมาชิกฟรีเพื่อบันทึกประวัติการสแกนและรับคำแนะนำเฉพาะสำหรับคุณ",
    "diagnosis.loginRequiredRegister": "สมัครสมาชิก",
    "diagnosis.loginRequiredLogin": "เข้าสู่ระบบ",
    "diagnosis.changeImage": "เปลี่ยนรูป",
    "diagnosis.loginToSaveHint": "โปรดเข้าสู่ระบบเพื่อบันทึกผลลัพธ์ลงประวัติ",

    // Auth
    "auth.welcomeTitle": "ยินดีต้อนรับสู่ AgriSense",
    "auth.welcomeSubtitle": "เข้าสู่บัญชีของคุณ",
    "auth.loginTitle": "เข้าสู่ระบบ",
    "auth.loginDescription": "กรอกอีเมลและรหัสผ่านเพื่อเข้าสู่บัญชีของคุณ",
    "auth.fillFieldsError": "กรุณากรอกข้อมูลให้ครบถ้วน",
    "auth.invalidError": "อีเมลหรือรหัสผ่านไม่ถูกต้อง",
    "auth.accountCreated": "สร้างบัญชีเรียบร้อยแล้ว กรุณาเข้าสู่ระบบ",
    "auth.signIn": "เข้าสู่ระบบ",
    "auth.signingIn": "กำลังเข้าสู่ระบบ...",
    "auth.noAccount": "ยังไม่มีบัญชี?",
    "auth.signUpHere": "สมัครสมาชิกที่นี่",
    "auth.registerTitle": "เข้าร่วม AgriSense",
    "auth.registerSubtitle": "สร้างบัญชีของคุณเพื่อเริ่มต้น",
    "auth.registerCardTitle": "สร้างบัญชี",
    "auth.registerCardDescription": "กรอกข้อมูลเพื่อสมัครสมาชิก",
    "auth.fullNameLabel": "ชื่อผู้ใช้",
    "auth.fullNamePlaceholder": "ชื่อผู้ใช้ของคุณ",
    "auth.emailLabel": "อีเมล",
    "auth.passwordLabel": "รหัสผ่าน",
    "auth.confirmPasswordLabel": "ยืนยันรหัสผ่าน",
    "auth.roleLabel": "บทบาท",
    "auth.role.farmer": "เกษตรกร",
    "auth.role.expert": "ผู้เชี่ยวชาญการเกษตร",
    "auth.registerButton": "สร้างบัญชี",
    "auth.registering": "กำลังสร้างบัญชี...",
    "auth.haveAccount": "มีบัญชีอยู่แล้ว?",
    "auth.signInHere": "เข้าสู่ระบบที่นี่",
    "auth.passwordMismatch": "รหัสผ่านไม่ตรงกัน",
    "auth.passwordTooShort": "รหัสผ่านต้องมีอย่างน้อย 6 ตัวอักษร",
    "auth.registerFailed": "สมัครสมาชิกไม่สำเร็จ กรุณาลองใหม่",

    // Knowledge Page
    "knowledge.title": "ความรู้การดูแลพืช",
    "knowledge.prevention": "การป้องกันโรค",
    "knowledge.watering": "แนวทางการรดน้ำ",
    "knowledge.fertilizer": "การใช้ปุ่ย",
    "knowledge.pest": "การควบคุมศัตรูพืช",

    // Disease Library
    "diseases.title": "คลังโรคพืชสำหรับผู้เชี่ยวชาญ",
    "diseases.subtitle":
      "ฐานข้อมูลภายในสำหรับผู้เชี่ยวชาญและผู้ดูแลระบบ Agrisense เพื่อใช้ประกอบการวิเคราะห์ AI",
    "diseases.searchLabel": "ค้นหา",
    "diseases.searchPlaceholder": "ค้นหาชื่อโรคหรืออาการ (ไทย/อังกฤษ)",
    "diseases.cropLabel": "ประเภทพืช",
    "diseases.filters.all": "ทุกพืช",
    "diseases.filters.durian": "ทุเรียน",
    "diseases.filters.sugarcane": "อ้อย",
    "diseases.filters.rice": "ข้าว",
    "diseases.loading": "กำลังโหลดข้อมูลโรคที่ผ่านการทวนสอบ...",
    "diseases.empty": "ยังไม่มีข้อมูลที่ตรงกับการค้นหา",
    "diseases.accessDeniedTitle": "จำกัดสิทธิ์เฉพาะผู้เชี่ยวชาญ",
    "diseases.accessDeniedDescription":
      "เฉพาะบัญชีผู้เชี่ยวชาญและแอดมินของ Agrisense เท่านั้นที่สามารถเข้าดูฐานข้อมูลโรคพืชนี้ได้",
    "diseases.contactCta": "ติดต่อผู้ดูแลระบบ",
    "diseases.spread.high": "ความเสี่ยงการระบาดสูง",
    "diseases.spread.medium": "ความเสี่ยงการระบาดปานกลาง",
    "diseases.spread.low": "ความเสี่ยงการระบาดต่ำ",
    "diseases.severityLabel": "ระดับความรุนแรง {score}/5",
    "diseases.symptoms": "อาการสำคัญ",
    "diseases.treatment": "แนวทางรับมือ",
    "diseases.prevention": "แนวทางป้องกัน",
    "diseases.noOverview": "ยังไม่มีคำอธิบายสำหรับโรคนี้",
    "diseases.causes": "ปัจจัยสาเหตุ",
    "diseases.addRecord": "เพิ่มข้อมูลโรค",
    "diseases.form.title": "เพิ่มข้อมูลโรคพืชใหม่",
    "diseases.form.description":
      "บันทึกรายละเอียดโรคพืชหลักของไทยเพื่อให้ผู้เชี่ยวชาญและโมเดล AI ใช้ประกอบการวิเคราะห์",
    "diseases.form.severity": "ระดับความรุนแรง (1-5)",
    "diseases.form.spreadRisk": "โอกาสการระบาด",
    "diseases.form.pathogenType": "ชนิดเชื้อสาเหตุ",
    "diseases.form.nameTh": "ชื่อภาษาไทย",
    "diseases.form.nameEn": "ชื่อภาษาอังกฤษ/สากล",
    "diseases.form.overview": "สรุปสั้น ๆ",
    "diseases.form.listPlaceholder": "พิมพ์ทีละบรรทัด",
    "diseases.form.listHelper": "แยกแต่ละข้อด้วยการขึ้นบรรทัดใหม่",
    "diseases.form.triggers": "สภาพกระตุ้นที่พบในแปลง",
    "diseases.form.tags": "แท็ก",
    "diseases.form.tagsHelper": "ขั้นด้วยเครื่องหมายจุลภาค เช่น leaf spot, fungal",
    "diseases.form.sources": "แหล่งอ้างอิง",
    "diseases.form.sourcesHelper": "ระบุรูปแบบ Label | https://example.com ต่อหนึ่งบรรทัด",
    "diseases.form.submit": "บันทึกข้อมูล",
    "diseases.form.missingRequired":
      "กรุณากรอกชื่อโรค อาการ สาเหตุ และวิธีการจัดการอย่างน้อย 1 รายการ",
    "diseases.form.genericError": "ไม่สามารถบันทึกข้อมูลโรคได้",

    // Dashboard
    "dashboard.title": "แดชบอร์ดผู้ใช้",
    "dashboard.adminProfilesTitle": "โปรไฟล์ผู้ดูแลระบบ",
    "dashboard.profile": "โปรไฟล์",
    "dashboard.history": "ประวัติผลสแกน",
    "dashboard.historyTitle": "ประวัติผลสแกน",
    "dashboard.alerts": "การแจ้งเตือนโรค",
    "dashboard.settings": "การตั้งค่า",
    "dashboard.loginPromptTitle": "กรุณาเข้าสู่ระบบ",
    "dashboard.loginPromptDescription": "ลงชื่อเข้าใช้งานเพื่อดูประวัติการวิเคราะห์และข้อมูลสถิติของคุณ",
    "dashboard.loginPromptHint": "หากคุณยังไม่มีบัญชีสามารถสมัครได้ฟรีเพื่อเริ่มบันทึกผลการวิเคราะห์พืชของคุณ",
    "dashboard.memberSince": "เป็นสมาชิกตั้งแต่",
    "dashboard.profileDescription": "ข้อมูลสมาชิกปัจจุบันและการตั้งค่าเบื้องต้น",
    "dashboard.anonymousUser": "ผู้ใช้งานไม่ระบุชื่อ",
    "dashboard.profilePlan": "แผนใช้งาน",
    "dashboard.manageProfile": "จัดการโปรไฟล์",
    "dashboard.defaultRole": "เกษตรกร",
    "dashboard.statsCardTitle": "การวิเคราะห์ล่าสุด",
    "dashboard.statsTotal": "จำนวนการสแกนทั้งหมด",
    "dashboard.statsCompleted": "การวิเคราะห์ที่เสร็จสิ้น",
    "dashboard.statsHealthy": "ผลที่ปกติ",
    "dashboard.statsHighRisk": "การแจ้งเตือนความเสี่ยงสูง",
    "dashboard.role.farmer": "เกษตรกร",
    "dashboard.role.expert": "ผู้เชี่ยวชาญการเกษตร",
    "dashboard.role.admin": "ผู้ดูแลระบบ",
    "dashboard.plan.free": "ฟรี",
    "dashboard.plan.pro": "โปร",
    "dashboard.plan.enterprise": "องค์กร",
    "dashboard.historyDescription": "รายการจะอัปเดตอัตโนมัติหลังจากการวิเคราะห์เสร็จสิ้น",
    "dashboard.status.pending": "รอดำเนินการ",
    "dashboard.status.processing": "กำลังประมวลผล",
    "dashboard.status.completed": "เสร็จสิ้น",
    "dashboard.status.failed": "ล้มเหลว",
    "dashboard.severity.high": "ความรุนแรงสูง",
    "dashboard.severity.medium": "ความรุนแรงปานกลาง",
    "dashboard.severity.low": "ความรุนแรงต่ำ",
    "dashboard.severity.none": "ไม่พบปัญหา",
    "dashboard.confidenceShort": "มีความน่าจะเป็นโรคนี้ {value}%",
    "dashboard.pendingAnalysis": "กำลังวิเคราะห์",
    "dashboard.loadingScans": "กำลังโหลดข้อมูล...",
    "dashboard.historyEmpty": "ยังไม่มีประวัติการวิเคราะห์ ลองเริ่มวิเคราะห์ภาพที่หน้าวินิจฉัย",
    "dashboard.unknownTime": "ไม่ทราบเวลา",
    "dashboard.viewDetails": "ดูรายละเอียดผลสแกน",
    "dashboard.deleteResult": "ลบผล",
    "dashboard.tipsTitle": "คำแนะนำล่าสุด",
    "dashboard.tipsDescription": "ส่วนนี้จะอัปเดตทุกครั้งเมื่อมีผลวิเคราะห์ใหม่",
    "dashboard.tipsBody": "ใช้แดชบอร์ดนี้เพื่อติดตามการวิเคราะห์แต่ละครั้ง ตรวจสอบสัญญาณความเสี่ยงสูง และตอบสนองต่อคำแนะนำจาก AI อย่างรวดเร็วเพื่อรักษาสุขภาพพืชของคุณ",
    "dashboard.tipsHint": "เคล็ดลับ: หากผลลัพธ์ซ้ำ ๆ ลองถ่ายหลายมุมและเพิ่มหมายเหตุเพื่อช่วยผู้เชี่ยวชาญวิเคราะห์เพิ่มเติม",
    "dashboard.profileDialogTitle": "จัดการโปรไฟล์",
    "dashboard.profileDialogDescription": "อัปโหลดหรือเปลี่ยนรูปโปรไฟล์ ระบบจะปรับขนาดให้อัตโนมัติ",
    "dashboard.profileDialogGuideline": "ใช้รูปสี่เหลี่ยมจัตุรัสไม่เกิน 4MB (JPG, PNG หรือ WEBP)",
    "dashboard.profileDialogInputLabel": "เลือกรูปใหม่",
    "dashboard.profileDialogInputHelp": "เราจะลดขนาดและบีบอัดรูปเพื่อไม่ให้สิ้นเปลืองพื้นที่จัดเก็บ",
    "dashboard.profileDialogSave": "บันทึกรูปภาพ",
    "dashboard.detailDialogTitle": "รายละเอียดผลสแกน",
    "dashboard.detailDialogDescription": "ดูข้อมูลเชิงลึกของผลการวิเคราะห์แต่ละครั้ง",
    "dashboard.detailResult": "ผลการตรวจ",
    "dashboard.detailStatus": "สถานะ",
    "dashboard.detailSeverity": "ความรุนแรง",
    "dashboard.detailConfidence": "ความมั่นใจ",
    "dashboard.detailSubmittedAt": "เวลาที่ส่งสแกน",
    "dashboard.detailProcessedAt": "เวลาที่ประมวลผล",
    "dashboard.detailCapturedAt": "เวลาถ่ายภาพ",
    "dashboard.detailModelVersion": "เวอร์ชันโมเดล",
    "dashboard.detailLocation": "สถานที่",
    "dashboard.detailLocationAccuracy": "±{meters} เมตร ของความแม่นยำ",
    "dashboard.detailFailureReason": "สาเหตุที่ล้มเหลว:",
    "dashboard.detailNotes": "หมายเหตุ",
    "dashboard.detailImage": "รูปภาพที่อัปโหลด",
    "dashboard.detailOpenFullImage": "เปิดรูปความละเอียดเต็ม",
    "dashboard.detailMetadata": "ข้อมูล Metadata",
    "dashboard.metadata.localeDisease": "ชื่อโรคในพื้นที่",
    "dashboard.metadata.severity": "ความรุนแรง",
    "dashboard.metadata.severityLocal": "ระดับความรุนแรง (ท้องถิ่น)",
    "dashboard.detailRawData": "ดูข้อมูลจากโมเดล (raw)",
    "dashboard.detailEmptyState": "เลือกผลการสแกนจากรายการด้านบน",
    "dashboard.deleteConfirmTitle": "ยืนยันการลบผลการสแกน",
    "dashboard.deleteConfirmDescription": "การลบผล \"{result}\" จะนำออกจากประวัติและไม่สามารถกู้คืนได้",
    "dashboard.deleteConfirmAction": "ลบผล",
    "dashboard.deletingStatus": "กำลังลบ...",
    "dashboard.uploadingAvatar": "กำลังอัปโหลด...",
    "dashboard.errorLoadHistory": "ไม่สามารถโหลดประวัติการวิเคราะห์ได้",
    "dashboard.errorLoadDetail": "ไม่สามารถดึงรายละเอียดการสแกนได้",
    "dashboard.errorDelete": "ไม่สามารถลบผลการสแกนได้ กรุณาลองใหม่อีกครั้ง",
    "dashboard.avatarErrorNotLoggedInTitle": "จำเป็นต้องเข้าสู่ระบบ",
    "dashboard.avatarErrorNotLoggedInDescription": "กรุณาเข้าสู่ระบบก่อนเปลี่ยนรูปโปรไฟล์",
    "dashboard.avatarErrorNoFileTitle": "ยังไม่ได้เลือกรูป",
    "dashboard.avatarErrorNoFileDescription": "กรุณาเลือกรูปที่ต้องการก่อนกดบันทึก",
    "dashboard.avatarErrorTypeTitle": "รูปแบบไฟล์ไม่รองรับ",
    "dashboard.avatarErrorTypeDescription": "กรุณาอัปโหลดไฟล์ PNG, JPG หรือ WEBP",
    "dashboard.avatarErrorSizeTitle": "ไฟล์มีขนาดใหญ่เกินไป",
    "dashboard.avatarErrorSizeDescription": "รูปโปรไฟล์ต้องมีขนาดไม่เกิน 4MB",
    "dashboard.avatarSuccessTitle": "บันทึกโปรไฟล์แล้ว",
    "dashboard.avatarSuccessDescription": "ระบบได้ปรับขนาดและบีบอัดรูปให้เหมาะสมเรียบร้อย",
    "dashboard.avatarFailTitle": "อัปโหลดไม่สำเร็จ",
    "dashboard.avatarFailDescription": "ไม่สามารถอัปโหลดรูปได้ กรุณาลองใหม่อีกครั้ง",
    "dashboard.note.healthy": "พืชดูสุขภาพดี ดูแลตามปกติและติดตามอย่างต่อเนื่อง",
    "dashboard.note.healthyShort": "พืชดูสุขภาพดี ดูแลตามปกติ",
    "dashboard.note.lowSeverity": "ตรวจพบความรุนแรงต่ำ ติดตามอาการและดูแลพืชให้ดีต่อเนื่อง",
    "dashboard.note.highSeverity": "พบความรุนแรงสูง ควรพิจารณาการรักษาทันทีและติดตามอาการอย่างใกล้ชิด",
    "dashboard.note.mediumSeverity": "พบความรุนแรงปานกลาง ควรเฝ้าสังเกตอย่างใกล้ชิดและพิจารณาการรักษาเฉพาะจุด",

    // About
    "about.title": "Agrisense คืออะไร",
    "about.p1":
      "Agrisense คือแพลตฟอร์มที่ใช้ AI ในการช่วยเกษตรกรและคนรักต้นไม้ตรวจวินิจฉัยโรคพืชได้อย่างรวดเร็วและแม่นยำจากการวิเคราะห์รูปภาพ",
    "about.p2":
      "เพียงอัปโหลดรูปภาพ ระบบจะแนะนำข้อมูลเชิงลึก วิธีดูแล และแนวทางป้องกันเพื่อให้พืชของคุณแข็งแรงได้ทุกที่ทุกเวลา",
    "about.p3":
      "ภารกิจของเราคือสนับสนุนการเกษตรอย่างยั่งยืนด้วยเทคโนโลยีอัจฉริยะ ทำให้การดูแลสุขภาพพืชเป็นเรื่องง่าย เข้าถึงได้ และมีประสิทธิภาพสำหรับทุกคน",
    "about.team": "ทีมของเรา",

    // Admin
    "admin.title": "แผงควบคุมผู้ดูแล",
    "admin.subtitle": "ใช้ช่องทางล็อกอินเดียวกันเพื่อควบคุมสิทธิ์ขั้นสูงและติดตามงานสำคัญ",
    "admin.diseases": "จัดการโรค",
    "admin.users": "จัดการผู้ใช้",
    "admin.userCardDescription": "อัปเกรดหรือปรับลดสิทธิ์ของสมาชิกได้ทันทีจากรายการนี้",
    "admin.analytics": "การวิเคราะห์ระบบ",
    "admin.alerts": "ส่งการแจ้งเตือน",
    "admin.loginRequiredTitle": "กรุณาเข้าสู่ระบบ",
    "admin.loginRequiredDescription": "แผงควบคุมนี้ใช้หน้าล็อกอินเดียวกับผู้ใช้ทั่วไป กรุณาเข้าสู่ระบบก่อนดำเนินการ",
    "admin.noPermissionTitle": "ต้องเป็นผู้ดูแลระบบ",
    "admin.noPermissionDescription": "เฉพาะบัญชีผู้ดูแลระบบเท่านั้นที่เข้าถึงหน้านี้ได้ โปรดให้ผู้ดูแลหลักเพิ่มสิทธิ์ให้คุณ",
    "admin.loadError": "ไม่สามารถโหลดรายชื่อผู้ใช้ได้",
    "admin.logLoadError": "ไม่สามารถโหลดบันทึกผู้ดูแลระบบได้",
    "admin.metrics.users": "จำนวนผู้ใช้ทั้งหมด",
    "admin.metrics.admins": "ผู้ดูแลระบบ",
    "admin.metrics.experts": "ผู้เชี่ยวชาญ",
    "admin.heroLabel": "ผู้ดูแล",
    "admin.heroTitle": "ศูนย์ควบคุม",
    "admin.heroSubtitle": "ดูแลสิทธิ์ผู้ใช้และข้อมูลสำคัญของแพลตฟอร์ม Agrisens ได้จากศูนย์ควบคุมเดียว",
    "admin.settingsPanelTitle": "การตั้งค่า",
    "admin.settingsPanelSubtitle": "ทางลัดไปยังเครื่องมือจัดการสำคัญ",
    "admin.notification": "การแจ้งเตือน",
    "admin.notification.allow": "อนุญาต",
    "admin.notification.mute": "ปิดเสียง",
    "admin.notificationStatusUpdated": "อัปเดตการตั้งค่าการแจ้งเตือนแล้ว",
    "admin.profileSaved": "บันทึกโปรไฟล์แล้ว",
    "admin.profileSavedDescription": "ข้อมูลจะซิงก์ไปยังคอนโซลผู้ดูแลทันที",
    "admin.profilePassword": "รหัสผ่านของคุณ",
    "admin.profileLocation": "พื้นที่",
    "admin.profileSaveCta": "บันทึกการเปลี่ยนแปลง",
    "admin.quickLinks.title": "เมนูลัดสำหรับงานหลัก",
    "admin.quickLinks.subtitle": "เข้าถึงเครื่องมือตรวจสอบที่สำคัญได้ทันที",
    "admin.quickLinks.logs": "บันทึกผู้ดูแล",
    "admin.quickLinks.logsDesc": "ดูการกระทำล่าสุดของผู้ดูแลระบบทุกคน",
    "admin.quickLinks.alerts": "ประกาศการแจ้งเตือนโรค",
    "admin.quickLinks.alertsDesc": "ไปยังศูนย์ประกาศเตือนโรคให้ผู้ใช้ (เชื่อมกับหน้าโปรไฟล์)",
    "admin.quickLinks.diseases": "คลังโรคพืช (เฉพาะผู้เชี่ยวชาญ)",
    "admin.quickLinks.diseasesDesc": "เปิดฐานข้อมูลโรคพืชไทยเพื่อทบทวนและเพิ่มข้อมูล",
    "admin.alertComposer.title": "ประกาศแจ้งเตือนโรค",
    "admin.alertComposer.description":
      "แจ้งเตือนโรคพืชสำคัญให้ผู้ใช้ทุกคนทราบ ข้อมูลจะปรากฏในหน้าการแจ้งเตือนโรคของโปรไฟล์",
    "admin.alertComposer.topic": "หัวข้อแจ้งเตือน",
    "admin.alertComposer.body": "รายละเอียด",
    "admin.alertComposer.image": "แนบรูปภาพ (ไม่บังคับ)",
    "admin.alertComposer.publish": "ประกาศแจ้งเตือน",
    "admin.alertComposer.success": "ประกาศแจ้งเตือนเรียบร้อย",
    "admin.alertComposer.error": "ไม่สามารถประกาศแจ้งเตือนได้",
    "admin.alertCenter.title": "ศูนย์ประกาศแจ้งเตือน",
    "admin.alertCenter.description": "ตรวจสอบประกาศก่อนหน้า ลบประกาศที่ไม่จำเป็น หรือสร้างประกาศใหม่ได้จากที่นี่",
    "admin.alertCenter.listTitle": "ประกาศที่เผยแพร่แล้ว",
    "admin.alertCenter.empty": "ยังไม่มีการประกาศแจ้งเตือน",
    "admin.alertCenter.newAlert": "สร้างประกาศใหม่",
    "admin.alertCenter.backToList": "กลับสู่ศูนย์ประกาศ",
    "admin.alertCenter.deleteSuccess": "ลบประกาศแล้ว",
    "admin.alertCenter.deleteError": "ไม่สามารถลบประกาศได้",
    "admin.alertCenter.publishedLabel": "เผยแพร่",
    "admin.quickLinks.roles": "จัดการผู้ใช้งาน",
    "admin.quickLinks.rolesDesc": "อนุมัติหรือยกเลิกสิทธิ์แอดมิน (จำกัดเฉพาะผู้ดูแลหลัก)",
    "admin.logRetentionNote": "ระบบจะเก็บทุกการกระทำของผู้ดูแลเพื่อให้ง่ายต่อการตรวจสอบ",
    "admin.roleManager.title": "จัดการสิทธิ์ผู้ใช้งาน",
    "admin.roleManager.subtitle":
      "มีเพียงบัญชีผู้ดูแลหลักที่ผ่านการอนุมัติเท่านั้นที่สามารถแต่งตั้งหรือปลดแอดมินได้",
    "admin.roleManager.permissionWarning":
      "ต้องเข้าสู่ระบบด้วยข้อมูลผู้ดูแลหลักจึงจะปรับสิทธิ์สมาชิกได้",
    "admin.roleManager.searchPlaceholder": "ค้นหาจากชื่อหรืออีเมล",
    "admin.roleManager.saveSuccess": "อัปเดตสิทธิ์เรียบร้อย",
    "admin.roleManager.saveError": "ไม่สามารถอัปเดตสิทธิ์ได้",
    "admin.roleManager.grantedAdmin": "ได้รับสิทธิ์เป็นผู้ดูแลระบบแล้ว",
    "admin.roleManager.revokedAdmin": "ถูกปรับกลับเป็นผู้ใช้งานทั่วไป",
    "admin.roleManager.auditHint": "ทุกการเปลี่ยนแปลงสิทธิ์จะถูกบันทึกในบันทึกผู้ดูแลระบบ",
    "admin.role.user": "ผู้ใช้งาน",
    "admin.role.admin": "ผู้ดูแลระบบ",
    "dashboard.alertsEmpty": "ยังไม่มีการประกาศแจ้งเตือนโรค",
    "admin.searchPlaceholder": "ค้นหาชื่อหรืออีเมล...",
    "admin.search": "ค้นหา",
    "admin.refresh": "รีเฟรช",
    "admin.table.name": "ชื่อ",
    "admin.table.email": "อีเมล",
    "admin.table.role": "บทบาท",
    "admin.table.plan": "แพ็กเกจ",
    "admin.table.joined": "เข้าร่วมเมื่อ",
    "admin.table.access": "สิทธิ์",
    "admin.emptyState": "ยังไม่พบผู้ใช้ที่ตรงเงื่อนไข ลองค้นหาใหม่",
    "admin.primaryBadge": "ผู้ดูแลหลัก",
    "admin.primaryInstructionsTitle": "บัญชีผู้ดูแลหลัก",
    "admin.primaryInstructionsDescription": "บัญชีผู้ดูแลหลักเป็นผู้ควบคุมการเพิ่มหรือลดสิทธิ์ผู้ดูแล",
    "admin.primaryInstructionsBody": "ติดต่อผู้รับผิดชอบหรือใช้ข้อมูลผู้ดูแลหลักเพื่อจัดการสิทธิ์ในรายการนี้",
    "admin.tip.signIn": "เข้าสู่ระบบด้วยข้อมูลผู้ดูแลที่ได้รับอนุญาตเพื่อปลดล็อกแผงควบคุม",
    "admin.primaryAccountLabel": "บัญชีผู้ดูแลหลัก (ข้อมูลปกป้อง)",
    "admin.tip.trust": "ให้สิทธิ์ผู้ดูแลเฉพาะสมาชิกที่ไว้ใจได้เท่านั้น",
    "admin.tip.downgrade": "ลดสิทธิ์ได้ทันทีเมื่อไม่จำเป็นต้องเข้าถึง",
    "admin.promoteSuccess": "อัปเดตสิทธิ์เรียบร้อย",
    "admin.promoteError": "ไม่สามารถอัปเดตสิทธิ์ได้",
    "admin.logTitle": "บันทึกการทำงานของผู้ดูแล",
    "admin.logDescription": "ระบบจะเก็บทุกการกระทำของผู้ดูแลเพื่อให้ง่ายต่อการตรวจสอบ",
    "admin.log.table.actor": "ผู้ดูแล",
    "admin.log.table.action": "การกระทำ",
    "admin.log.table.target": "เป้าหมาย",
    "admin.log.table.timestamp": "เวลา",
    "admin.log.empty": "ยังไม่มีบันทึกผู้ดูแล",
    "admin.log.loading": "กำลังโหลดบันทึกผู้ดูแล...",
    "admin.log.action.promote": "เพิ่มสิทธิ์ผู้ดูแล",
    "admin.log.action.demote": "ลดสิทธิ์ผู้ดูแล",
    "admin.log.action.update": "ปรับบทบาท",
    "admin.log.action.custom": "การกระทำผู้ดูแล",
    "admin.log.action.alertPublish": "ประกาศแจ้งเตือนโรค",
    "admin.log.unknownTarget": "ไม่ทราบเป้าหมาย",

    // Common
    "common.save": "บันทึก",
    "common.cancel": "ยกเลิก",
    "common.edit": "แก้ไข",
    "common.delete": "ลบ",
    "common.loading": "กำลังโหลด...",
    "common.name": "ชื่อ",
    "common.refresh": "รีเฟรช",
    "common.error": "เกิดข้อผิดพลาด",
    "common.success": "สำเร็จ",
    "common.close": "ปิด",
  },
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

const DEFAULT_LANGUAGE: Language = "th"

const loadStoredLanguage = (): Language | null => {
  if (typeof window === "undefined") {
    return null
  }
  const savedLanguage = localStorage.getItem("agrisense-language") as Language | null
  return savedLanguage === "en" || savedLanguage === "th" ? savedLanguage : null
}

export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<Language>(() => loadStoredLanguage() ?? DEFAULT_LANGUAGE)

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang)
    if (typeof window !== "undefined") {
      localStorage.setItem("agrisense-language", lang)
    }
  }

  const t = (key: string): string => {
    return translations[language][key as keyof (typeof translations)[typeof language]] || key
  }

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  )
}

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider")
  }
  return context
}
